language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t talelia140897/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true talelia140897/docker-react npm run test -- -- coverage